-- Generated by scripts/generate-seed.ts — do not edit by hand.
-- Regenerate with `npm run seed:generate`.
--
-- Loaded by `supabase db reset`. Rows here are reference data only: profiles and
-- preferences are provisioned per signup by handle_auth_user_change().
insert into public.schools (name, short_name, email_domains) values
  ('Arizona State University', 'ASU', array['asu.edu']::extensions.citext[]),
  ('Carnegie Mellon University', 'CMU', array['cmu.edu', 'andrew.cmu.edu']::extensions.citext[]),
  ('Georgia Institute of Technology', 'Georgia Tech', array['gatech.edu']::extensions.citext[]),
  ('Massachusetts Institute of Technology', 'MIT', array['mit.edu']::extensions.citext[]),
  ('Purdue University', 'Purdue', array['purdue.edu']::extensions.citext[]),
  ('Stanford University', 'Stanford', array['stanford.edu']::extensions.citext[]),
  ('University of California, Berkeley', 'Berkeley', array['berkeley.edu']::extensions.citext[]),
  ('University of Illinois Urbana-Champaign', 'UIUC', array['illinois.edu']::extensions.citext[]),
  ('University of Michigan', 'Michigan', array['umich.edu']::extensions.citext[]),
  ('University of Texas at Austin', 'UT Austin', array['utexas.edu']::extensions.citext[]),
  ('University of Texas at Dallas', 'UT Dallas', array['utdallas.edu']::extensions.citext[]),
  ('University of Washington', 'UW', array['uw.edu']::extensions.citext[])
on conflict (name) do update set
  short_name = excluded.short_name,
  email_domains = excluded.email_domains;
