/*
 * Writes supabase/seed.sql from the app's own fixtures.
 *
 * §2.2: "The mock fixtures become the seed script. They're good fixtures — keep them
 * working so local dev never needs a crawler." Phase 0 only owns `schools`, so that is
 * all this emits; companies and jobs join it in phase 1 from data/mockCompanies.ts and
 * data/mockJobs.ts.
 *
 * Run with `npm run seed:generate`. Node strips the types, so this imports the very
 * same fixture module the app does rather than a copy that can drift from it.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { mockUser } from '../data/mockUser.ts';

interface SchoolSeed {
  name: string;
  shortName: string;
  emailDomains: string[];
}

/*
 * Enough US schools to exercise the .edu matching in §3.2 and to make the school field
 * feel real in local dev. This is not the production list — that one gets imported from
 * IPEDS in phase 3, when `.edu` verification actually needs full coverage.
 */
const SCHOOLS: SchoolSeed[] = [
  { name: 'University of Texas at Dallas', shortName: 'UT Dallas', emailDomains: ['utdallas.edu'] },
  { name: 'University of Texas at Austin', shortName: 'UT Austin', emailDomains: ['utexas.edu'] },
  { name: 'Purdue University', shortName: 'Purdue', emailDomains: ['purdue.edu'] },
  { name: 'Georgia Institute of Technology', shortName: 'Georgia Tech', emailDomains: ['gatech.edu'] },
  { name: 'University of Illinois Urbana-Champaign', shortName: 'UIUC', emailDomains: ['illinois.edu'] },
  { name: 'University of Michigan', shortName: 'Michigan', emailDomains: ['umich.edu'] },
  { name: 'Carnegie Mellon University', shortName: 'CMU', emailDomains: ['cmu.edu', 'andrew.cmu.edu'] },
  { name: 'Massachusetts Institute of Technology', shortName: 'MIT', emailDomains: ['mit.edu'] },
  { name: 'Stanford University', shortName: 'Stanford', emailDomains: ['stanford.edu'] },
  { name: 'University of California, Berkeley', shortName: 'Berkeley', emailDomains: ['berkeley.edu'] },
  { name: 'University of Washington', shortName: 'UW', emailDomains: ['uw.edu'] },
  { name: 'Arizona State University', shortName: 'ASU', emailDomains: ['asu.edu'] },
];

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function citextArray(values: string[]): string {
  if (values.length === 0) return `'{}'::extensions.citext[]`;
  return `array[${values.map(quote).join(', ')}]::extensions.citext[]`;
}

function schoolsSql(schools: SchoolSeed[]): string {
  const rows = schools
    .map((school) => `  (${quote(school.name)}, ${quote(school.shortName)}, ${citextArray(school.emailDomains)})`)
    .join(',\n');

  // Idempotent so `supabase db reset` and a re-run against a warm database behave the
  // same. `schools.name` is the natural key; the uuid is generated.
  return [
    'insert into public.schools (name, short_name, email_domains) values',
    rows,
    'on conflict (name) do update set',
    '  short_name = excluded.short_name,',
    '  email_domains = excluded.email_domains;',
  ].join('\n');
}

const schools = [...SCHOOLS];

// The fixture user has to be able to pick their own school, or local dev diverges from
// the app the moment someone opens Profile.
if (!schools.some((school) => school.name === mockUser.school)) {
  schools.push({ name: mockUser.school, shortName: mockUser.school, emailDomains: [] });
}

schools.sort((a, b) => a.name.localeCompare(b.name));

const header = [
  '-- Generated by scripts/generate-seed.ts — do not edit by hand.',
  '-- Regenerate with `npm run seed:generate`.',
  '--',
  '-- Loaded by `supabase db reset`. Rows here are reference data only: profiles and',
  '-- preferences are provisioned per signup by handle_auth_user_change().',
  '',
].join('\n');

const outputPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'supabase', 'seed.sql');
writeFileSync(outputPath, `${header}${schoolsSql(schools)}\n`, 'utf8');

console.log(`Wrote ${outputPath} (${schools.length} schools)`);
